
name: campus_pulse
description: "Campus Pulse â€“ Smart Emergency Alert System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2

  # Firebase Core
  firebase_core: ^4.4.0

  # Authentication
  firebase_auth: ^6.1.4

  # Database
  cloud_firestore: ^6.1.2

  # State Management
  provider: ^6.1.5+1

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
